name: Publish to PyPI

on: 
  push:
    branches: [release]
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
        id-token: write
    environment:
        name: release
        url: https://pypi.org/p/streamlit-custom-filters

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install full package
        run: |
          python -m venv venv
          . ./venv/bin/activate
          pip install --upgrade pip wheel poetry
          poetry cache clear pypi --all
          poetry install --no-dev

      - name: Build
        run: |
            . ./venv/bin/activate
            poetry build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
