name: Publish to test PyPI

on: 
    push:
        branches: ["main"]

jobs:
  
  publish_test:
    runs-on: ubuntu-22.04
    permissions:
        id-token: write
    environment:
        name: testpypi
        url: https://test.pypi.org/p/streamlit-custom-filters

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install full package
        run: |
          python -m venv venv
          . ./venv/bin/activate
          pip install --upgrade pip wheel poetry
          poetry cache clear pypi --all
          poetry install --no-dev

      - name: Build
        run: |
            . ./venv/bin/activate
            poetry build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with: 
          repository-url: https://test.pypi.org/legacy/